CREATE TABLE `venues` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` text CHARACTER SET utf8 NOT NULL,
  `type` text CHARACTER SET utf8 NOT NULL,
  `location` text CHARACTER SET utf8 NOT NULL,
  `longitude` text CHARACTER SET utf8 NOT NULL,
  `latitude` text CHARACTER SET utf8 NOT NULL,
  `reviewScore` float NOT NULL,
  `ratingStar` int(11) NOT NULL,
  `offerExists` int(11) NOT NULL,
  `descrip` text CHARACTER SET utf8 NOT NULL,
  `offerTitle` text NOT NULL,
  `offerDescription` text CHARACTER SET utf8 NOT NULL,
  `isPoolAvailable` int(11) NOT NULL,
  `isGymAvailable` int(11) NOT NULL,
  `isWifiAvailable` int(11) NOT NULL,
  `isVisaPaymentAvailable` int(11) NOT NULL,
  `isDiningInAvailable` int(11) NOT NULL,
  `accomadtionType` text CHARACTER SET utf8 NOT NULL,
  `elgounaVoice` text CHARACTER SET utf8 NOT NULL,
  `email` text CHARACTER SET utf8 NOT NULL,
  `phoneNumber` text CHARACTER SET utf8 NOT NULL,
  `info` text CHARACTER SET utf8 NOT NULL,
  `facebookLink` text CHARACTER SET utf8 NOT NULL,
  `twitterLink` text CHARACTER SET utf8 NOT NULL,
  `instagramLink` text CHARACTER SET utf8 NOT NULL,
  `youtubeLink` text CHARACTER SET utf8 NOT NULL,
  `ord` int(11) NOT NULL,
  `hidden` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `id` (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=12 DEFAULT CHARSET=latin1
