<?php 
session_start();
include("check_session.php");
include("../db_conn.php");
if(isset($_POST['bookingURL'])){
date_default_timezone_set('Africa/Cairo');
$date=date("Y-m-d");
$bookingURL=mysql_real_escape_string($_POST['bookingURL']);
$facebookURL=mysql_real_escape_string($_POST['facebookURL']);
$twitterURL=mysql_real_escape_string($_POST['twitterURL']);
$elgounaURL=mysql_real_escape_string($_POST['elgounaURL']);
$instagramURL=mysql_real_escape_string($_POST['instagramURL']);
$snapchatURL=mysql_real_escape_string($_POST['snapchatURL']);
$youtubeURL=mysql_real_escape_string($_POST['youtubeURL']);
$elgounaSMS=mysql_real_escape_string($_POST['elgounaSMS']);
$elgounaPhone=mysql_real_escape_string($_POST['elgounaPhone']);
$elgounaemail=mysql_real_escape_string($_POST['elgounaemail']);
$about=mysql_real_escape_string($_POST['about']);

$sql="update booking_link set `bookingURL`='$bookingURL',facebookURL='$facebookURL',twitterURL='$twitterURL',elgounaURL='$elgounaURL',instagramURL='$instagramURL',youtubeURL='$youtubeURL',elgounaSMS='$elgounaSMS',elgounaPhone='$elgounaPhone',elgounaemail='$elgounaemail',snapchatURL='$snapchatURL',about='$about'  where id='1'";
$r=mysql_query($sql);
if($r){
header("location:booking.php?fl=1");
}else{
header("location:booking.php?fl=2");
}}else{
header("location:booking.php?fl=3");
}
?>